### ISSUE TITLE
Create 404 not found page 

### ISSUE THREAD

**Issue by dipu-s-repo68** [dipu-s-repo68/hacktoberfest_2024_first.github.io#3]

**Comment by adityabavadekar** [comment]
Hi @dipu-s-repo68 , I would like to contribute to this.

**Comment by SnehaghoshBarsha444** [comment]
Hi sir @dipu-s-repo68 ,
I'm eager to do it
Can you assign me ?

**Comment by dipu-s-repo68** [comment]
@AdityaBavadekar , @SnehaghoshBarsha444  
both of you do at first then I'll check it out and then the right one will be merged

**Comment by dipu-s-repo68** [comment]
@AdityaBavadekar        ,
                        @SnehaghoshBarsha444 has already done it. 
thanks everyone
